sort active votes #1830
GolosChain/tolstoy pull request #1837
Opened 2018-12-19 16:00 UTC by b1acksun

2018-12-19 16:01 UTC, bacher approved these changes

2018-12-19 17:25 UTC, AlexRekish approved these changes

2018-12-20 08:34 UTC, bacher requested changes

2018-12-20 08:34 UTC, Bacher commented on app/utils/StateFunctions.js
> +    return Math.abs(parseInt(b.get('rshares'))) - Math.abs(parseInt(a.get('rshares')));
Тут Math.abs в конце нельзя использовать, он ломает сортировку.

Сортировка должна выдавать отрицательные положительные и ноль. А тут все по сути положительные будут.

2018-12-20 08:40 UTC, Bacher commented on app/utils/StateFunctions.js
> +    return Math.abs(parseInt(b.get('rshares'))) - Math.abs(parseInt(a.get('rshares')));
Ой, сорян, ошибся.

2018-12-20 08:40 UTC, bacher approved these changes

2018-12-20 09:04 UTC, merged