1211 adapt text editor
GolosChain/tolstoy pull request #1851
Opened 2018-12-20 15:25 UTC by AlexRekish

2018-12-20 16:52 UTC, bacher requested changes

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostFooter/PostFooter.jsx
> +    appearance: none;
Мне кажется будет достаточно, у нас там autoprefixer встроенный.
```
appearance: none;
```

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostFooter/PostFooter.jsx
> +                                    onClick={editMode ? onCancelClick : onResetClick}
Обработчики событий лучше располагать в конце списка атрибутов.

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostFooter/PostFooter.jsx
> +                                    onPreviewChange={onPreviewChange}
В конец тоже.

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostFooter/PostFooter.jsx
> +                                    onClick={this.props.onPostClick}
Тут тоже лучше в конце перенести.

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostOptions/PostOptions.jsx
> +        color: #333333 !important;
`!important` очень стремно

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/PostOptions/PostOptions.jsx
> +        color: #333333 !important;
Можно ли как-то описать по другому?

2018-12-20 16:52 UTC, Bacher commented on app/components/elements/postEditor/TagInput/index.jsx
> +    font-stretch: normal;
Действительно ли нужно обнулять стили? Они переопределяются где-то?

2018-12-20 16:52 UTC, Bacher commented on src/app/components/header/Header/Header.jsx
> +        `};
Выравнивание `};`

2018-12-21 08:22 UTC, bacher approved these changes

2018-12-21 08:31 UTC, beautyfree approved these changes

2018-12-21 08:50 UTC, b1acksun approved these changes

2018-12-21 09:17 UTC, merged