1871 fix title value after clear
GolosChain/tolstoy pull request #1873
Opened 2018-12-22 11:47 UTC by AlexRekish

2018-12-22 11:48 UTC, b1acksun approved these changes

2018-12-22 11:54 UTC, Nikita-Pobazhak approved these changes

2018-12-24 09:52 UTC, beautyfree approved these changes

2018-12-24 11:45 UTC, bacher requested changes

2018-12-24 11:45 UTC, Bacher commented on app/components/elements/postEditor/PostTitle/PostTitle.jsx
> +        if (!initialValue && this.inputRef && this.inputRef.current) {
Нет смысла проверять на `this.inputRef && this.inputRef.current`, это только заставляет задуматься о том почему его может не быть.

Я правильно понимаю, его не может не быть?

2018-12-24 11:45 UTC, Bacher commented on app/components/elements/postEditor/PostTitle/PostTitle.jsx
> +            this.inputRef && this.inputRef.current
Не вижу условия когда может не быть `this.inputRef.current`.

2018-12-25 13:25 UTC, bacher approved these changes

2018-12-25 13:41 UTC, merged