1770 user online status
GolosChain/tolstoy pull request #1895
Opened 2018-12-26 17:21 UTC by Bacher

2018-12-27 08:14 UTC, AlexRekish requested changes

2018-12-27 08:14 UTC, AlexRekish commented on src/app/components/userProfile/common/UserHeader/UserHeader.jsx
> +    height: 100%;
тут или должен быть min-height или что-то лишнее

2018-12-27 08:14 UTC, AlexRekish commented on src/app/redux/sagas/userOnline.js
> +    console.log('LOGOUT');
console.log

2018-12-27 08:14 UTC, AlexRekish commented on src/app/components/userProfile/common/OnlineStatus/OnlineStatus.jsx
> +        this.props.fetchUserLastOnline(username, lastOnlineTs => {
лучше тоже вынести в деструктуризацию выше

2018-12-27 08:21 UTC, Bacher commented on src/app/components/userProfile/common/OnlineStatus/OnlineStatus.jsx
> +        this.props.fetchUserLastOnline(username, lastOnlineTs => {
Мы обсуждали эту тему в слаке, жаркое обсуждение, сошлись на том что вызывать функции напрямую из props допускается, многие считают что это более явно (я в том числе).

2018-12-27 08:22 UTC, Bacher commented on src/app/components/userProfile/common/UserHeader/UserHeader.jsx
> +    height: 100%;
Точняк =)

2018-12-27 08:30 UTC, AlexRekish approved these changes

2018-12-27 14:59 UTC, beautyfree requested changes

2018-12-27 14:59 UTC, beautyfree commented on src/app/components/userProfile/common/OnlineStatus/OnlineStatus.connect.js
> +        fetchUserLastOnline: (username, callback) => async () => {
Раз уж такая реализация, то хотя бы вынести в экшен, а не прокидывать хэлперы работы с вебсокетами в коннект

2018-12-28 09:16 UTC, beautyfree approved these changes

2018-12-28 09:17 UTC, b1acksun approved these changes

2018-12-28 11:04 UTC, merged