1804 redesign witnesses page
GolosChain/tolstoy pull request #1913
Opened 2018-12-29 09:40 UTC by Nikita-Pobazhak

2018-12-29 09:54 UTC, AlexRekish requested changes

2018-12-29 09:54 UTC, AlexRekish commented on src/app/containers/Witnesses/Witnesses.jsx
> +            !is(np.witnessVotes, this.props.witnessVotes) ||
тут и ниже можно пропсы и стейт в деструктуризацию вынести

2018-12-29 09:54 UTC, AlexRekish commented on src/app/containers/Witnesses/Witnesses.jsx
> +                                        style={{
тут стоит вынести объект со стилями за компонент и передавать ссылку, чтобы избежать лишнего ререндера

2018-12-29 11:31 UTC, AlexRekish approved these changes

2019-01-09 09:12 UTC, b1acksun approved these changes

2019-01-09 09:15 UTC, beautyfree approved these changes

2019-01-09 09:31 UTC, merged