1829 show qr button
GolosChain/tolstoy pull request #1948
Opened 2019-01-22 11:27 UTC by Nikita-Pobazhak

2019-01-22 12:50 UTC, bacher requested changes

2019-01-22 12:50 UTC, Bacher commented on src/app/components/userProfile/settings/keys/Current/ShowKey.js
> +        return <ButtonStyled onClick={this.handleShowQr}>показать QR</ButtonStyled>;
Локализация

2019-01-23 09:04 UTC, beautyfree approved these changes

2019-01-23 11:13 UTC, AlexRekish approved these changes

2019-01-23 12:05 UTC, b1acksun approved these changes

2019-01-23 13:35 UTC, bacher approved these changes

2019-01-23 13:58 UTC, merged