1042 link to Golos Explorer
GolosChain/tolstoy pull request #1949
Opened 2019-01-22 12:48 UTC by Nikita-Pobazhak

2019-01-22 12:51 UTC, bacher requested changes

2019-01-22 12:51 UTC, Bacher commented on src/app/components/golos-ui/Icon/assets/golos_explorer.svg
> +<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
svgo

2019-01-23 09:04 UTC, beautyfree approved these changes

2019-01-23 11:14 UTC, AlexRekish approved these changes

2019-01-23 12:06 UTC, b1acksun approved these changes

2019-01-23 13:35 UTC, bacher approved these changes

2019-01-23 13:58 UTC, merged