1955 fix post footer
GolosChain/tolstoy pull request #1969
Opened 2019-01-30 15:09 UTC by Nikita-Pobazhak

2019-01-30 15:09 UTC, b1acksun approved these changes

2019-01-30 15:18 UTC, bacher requested changes

2019-01-30 15:18 UTC, Bacher commented on src/app/components/cards/PostCard/PostCard.jsx
> +        margin-left: 20px;
А если три иконки? То у средней не будет отступа.

2019-01-30 15:18 UTC, Bacher commented on src/app/components/cards/PostCard/PostCard.jsx
> +        margin-left: 20px;
Три иконки есть когда смотришь на свои посты.

2019-01-30 17:47 UTC, Nikita-Pobazhak commented on src/app/components/cards/PostCard/PostCard.jsx
> +        margin-left: 20px;
не понял где 3 иконки, это же количество просмотров и процент кураторских

2019-01-31 09:05 UTC, Bacher commented on src/app/components/cards/PostCard/PostCard.jsx
> +        margin-left: 20px;
Перепутал контейнеры, но всё равно странно, если в будущем добавится 3я иконка придется опять стили менять.
Но сейчас приму.

2019-01-31 09:06 UTC, bacher approved these changes

2019-01-31 09:44 UTC, AlexRekish approved these changes

2019-01-31 10:06 UTC, merged