fixes in converter modal
GolosChain/tolstoy pull request #1980
Opened 2019-02-14 11:44 UTC by Nikita-Pobazhak

2019-02-14 11:57 UTC, bacher requested changes

2019-02-14 11:57 UTC, Bacher commented on src/app/components/golos-ui/Slider/Slider.js
> +    `} &:before {
Стили сбились

2019-02-14 12:25 UTC, AlexRekish approved these changes

2019-02-14 12:52 UTC, b1acksun approved these changes

2019-02-18 11:05 UTC, beautyfree approved these changes

2019-02-22 09:32 UTC, bacher approved these changes

2019-02-25 13:27 UTC, merged